### ISSUE TITLE
Error with party

### ISSUE THREAD

**Issue by brutalzinn** [Simonsator/BungeecordPartyAndFriends#15]
I bought the plugin for the spigot version. But I am having errors when I execute the command / party invite

i'm using 1.7.10 kcauldron.
```
[13:17:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'party invite abacate' in de.simonsator.partyandfriends.party.command.PartyCommand(party)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1448.121]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1448.121]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at de.simonsator.partyandfriends.party.PartyManager.createParty(PartyManager.java:52) ~[?:?]
	at de.simonsator.partyandfriends.party.command.Invite.onCommand(Invite.java:89) ~[?:?]
	at de.simonsator.partyandfriends.party.command.PartyCommand.onCommand(PartyCommand.java:178) ~[?:?]
	at de.simonsator.partyandfriends.api.commands.PartyFriendCommand.execute(PartyFriendCommand.java:21) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1448.121]
	... 12 more
```

**Comment by Simonsator** [comment]
Since the bungeecord version is another plugin this is not the right place to report a problem
